### ISSUE TITLE
static IP configuration

### ISSUE THREAD

**Issue by zainurihasan** [nopnop2002/esp8266_ethernet#3]
how to configure the Static IP?, in my network i need to configure esp with static IP

**Comment by nopnop2002** [comment]
```
#include <SPI.h>
#include <ESP8266WiFi.h>
#include <ESP8266mDNS.h>
#include <W5500lwIP.h>

#define CSPIN 16

Wiznet5500lwIP eth(CSPIN);
byte mac[] = {0x00, 0xAA, 0xBB, 0xCC, 0xDE, 0x02};

#define STATIC

void setup()
{
  Serial.begin(115200);

  SPI.begin();
  SPI.setBitOrder(MSBFIRST);
  SPI.setDataMode(SPI_MODE0);
  SPI.setFrequency(4000000);

  eth.setDefault(); // use ethernet for default route

#ifdef STATIC
  IPAddress ip(192,168,10,130);   
  IPAddress gateway(192,168,10,1);   
  IPAddress subnet(255,255,255,0);   
  eth.config(ip, gateway, subnet);
#endif

  int present = eth.begin(mac);
  if (!present) {
    Serial.println("no ethernet hardware present");
    while (1);
  }

  Serial.println();
  Serial.print("ethernet ip address: ");
  Serial.println(eth.localIP());
  Serial.print("ethernet subnetMask: ");
  Serial.println(eth.subnetMask());
  Serial.print("ethernet gateway: ");
  Serial.println(eth.gatewayIP());
}
```

**Comment by zainurihasan** [comment]
thanks for your replay, i have try add the static config but i got this error     

 no matching function for call to 'LwipIntfDev<ENC28J60>::config(IPAddress&, IPAddress&, IPAddress&)'

i use ENC28j60 modul

i hope you can helpme  thanks

**Comment by nopnop2002** [comment]
Please show me all your code.

**Comment by zainurihasan** [comment]
i just try to compileit but i got that error, 
```
#include <SPI.h>
#include <ESP8266WiFi.h>
#include <ESP8266mDNS.h>
#include <ENC28J60lwIP.h>

#define CSPIN 2

ENC28J60lwIP eth(CSPIN);
byte mac[] = {0x00, 0xAA, 0xBB, 0xCC, 0xDE, 0x02};

#define STATIC

void setup()
{
  Serial.begin(115200);

  SPI.begin();
  SPI.setBitOrder(MSBFIRST);
  SPI.setDataMode(SPI_MODE0);
  SPI.setFrequency(4000000);

  eth.setDefault(); // use ethernet for default route

#ifdef STATIC
  IPAddress ip(192,168,10,130);   
  IPAddress gateway(192,168,10,1);   
  IPAddress subnet(255,255,255,0);   
  eth.config(ip, gateway, subnet);
#endif

  int present = eth.begin(mac);
  if (!present) {
    Serial.println("no ethernet hardware present");
    while (1);
  }

  Serial.println();
  Serial.print("ethernet ip address: ");
  Serial.println(eth.localIP());
  Serial.print("ethernet subnetMask: ");
  Serial.println(eth.subnetMask());
  Serial.print("ethernet gateway: ");
  Serial.println(eth.gatewayIP());
}```

**Comment by nopnop2002** [comment]
No error in my environment.

```
void setup() {
  Serial.begin(115200);
  Serial.println();
  Serial.print("ARDUINO_BOARD=");
  Serial.print(ARDUINO_BOARD);
  Serial.println();
  Serial.print("ESP.getFullVersion=");
  Serial.print(ESP.getFullVersion());
  Serial.println();
  Serial.print("ESP.getCoreVersion=");
  Serial.print(ESP.getCoreVersion());
  Serial.println();
}

void loop() {
}
```

```
ARDUINO_BOARD=ESP8266_WEMOS_D1MINI
ESP.getFullVersion=SDK:2.2.2-dev(38a443e)/Core:3.0.2=30002000/lwIP:STABLE-2_1_2_RELEASE/glue:1.2-48-g7421258/BearSSL:6105635
ESP.getCoreVersion=3.0.2
```

**Comment by zainurihasan** [comment]
> No error in my environment.
> 
> ```
> void setup() {
>   Serial.begin(115200);
>   Serial.println();
>   Serial.print("ARDUINO_BOARD=");
>   Serial.print(ARDUINO_BOARD);
>   Serial.println();
>   Serial.print("ESP.getFullVersion=");
>   Serial.print(ESP.getFullVersion());
>   Serial.println();
>   Serial.print("ESP.getCoreVersion=");
>   Serial.print(ESP.getCoreVersion());
>   Serial.println();
> }
> 
> void loop() {
> }
> ```
> 
> ```
> ARDUINO_BOARD=ESP8266_WEMOS_D1MINI
> ESP.getFullVersion=SDK:2.2.2-dev(38a443e)/Core:3.0.2=30002000/lwIP:STABLE-2_1_2_RELEASE/glue:1.2-48-g7421258/BearSSL:6105635
> ESP.getCoreVersion=3.0.2
> ```

thanks it work, i update the esp8266 library on the arduino IDE to the latest version

**Comment by zainurihasan** [comment]
hi sorry open this issue again, after i try it,  the ethernet got the static ip and i success pingit, but the device cant request data.
if i switch to DHCP , it working properly.

**Comment by nopnop2002** [comment]
It is necessary to set dns when communicating with the outside.

```
#ifdef STATIC
  IPAddress ip(192,168,10,130);   
  IPAddress gateway(192,168,10,1);   
  IPAddress subnet(255,255,255,0);
  IPAddress dns(192,168,10,1);
  WiFi.config(ip, gateway, subnet, dns);
#endif
```

**Comment by zainurihasan** [comment]
> It is necessary to set dns when communicating with the outside.
> 
> ```
> #ifdef STATIC
>   IPAddress ip(192,168,10,130);   
>   IPAddress gateway(192,168,10,1);   
>   IPAddress subnet(255,255,255,0);
>   IPAddress dns(192,168,10,1);
>   WiFi.config(ip, gateway, subnet, dns);
> #endif
> ```

ok, it solved,
