### ISSUE TITLE
help for understand the code

### ISSUE THREAD

**Issue by wfrm** [nopnop2002/esp8266_ethernet#4]
hi,
Cheers,
I would like to understand in a general way how this code works. Could you please help me, recommending books or other base codes?

**Comment by nopnop2002** [comment]
Do you understand ESP8266 WiFi and LWIP? 

There is a lot of information on th web about ESP8266 WiFi and LWIP.

This sample simply replaces the WiFi driver with an Ethernet driver.

I can't explain any more.

If you would like to know more, please contact EspressIF.

**Comment by wfrm** [comment]
thanks for answering,
I have managed to get the esp8266 to connect via ethernet with the w5100
chip
but when a client enters the esp restarts.

(  is it better to open a case on github?)

the serial monitor indicates this:


Server Start. Wait for Client
myDomainName: ESP_27C9FD
mDNS responder started
new client
TCP Server Receive Size=471

--------------- CUT HERE FOR EXCEPTION DECODER ---------------

**Comment by nopnop2002** [comment]
You need to change this depending on the data size

https://github.com/nopnop2002/esp8266_ethernet/blob/master/TCP_Server/TCP_Server.ino#L95

```
  char smsg[30];
  char rmsg[30];
```

**Comment by wfrm** [comment]
I am very grateful for your valuable collaboration.
I wish you many blessings.
greetings from Bogota, Colombia
