### ISSUE TITLE
Using spi ethernet module with wifi at the same time

### ISSUE THREAD

**Issue by jimmorrisson** [nopnop2002/esp8266_ethernet#5]
Hi, is it possible to use SPI ethernet module and WIFI connection at the same time? I would like to have a Modbus client which would use SPI module and MQTT client that would use WIFI and was wondering if it's possible at all (since it's not stated in the readme).
Thanks in advance for help :)

**Comment by nopnop2002** [comment]
I haven't tried it, but it might work.

**Comment by nopnop2002** [comment]
I tried.
Work fine.
```
SDK:2.2.2-dev(38a443e)/Core:3.1.2=30102000/lwIP:STABLE-2_1_3_RELEASE/glue:1.2-65-g06164fb/BearSSL:b024386
connecting ethernet...
connecting wifi....
Ethernet.localIP: 192.168.10.113
WiFi.localIP: 192.168.10.115
Ethernet.localIP: 192.168.10.113
WiFi.localIP: 192.168.10.115
Ethernet.localIP: 192.168.10.113
WiFi.localIP: 192.168.10.115
Ethernet.localIP: 192.168.10.113
WiFi.localIP: 192.168.10.115
```

https://github.com/nopnop2002/esp8266_ethernet/tree/master/connectEthernetAndWiFi
