### ISSUE TITLE
NodeMCU v3 (LOLIn) doesn't work with W5500

### ISSUE THREAD

**Issue by AlekseyCanvas** [nopnop2002/esp8266_ethernet#6]
I connected the W5500 to NodeMCU v3 (LoLin) via SPI (D5, D6, D7, D8), but NodeMCU v3 does not run the code. This happens when the CS W5500 pin is connected to the D8 W5500 pin. I tried to connect SY to another pin on NodeMCU m3 and reassigned pennies in the code using Wiznet5500lwIP eth(CS PING), NodeMCU v3 runs the code, but W5500 itself does not detect.

**Comment by AlekseyCanvas** [comment]
After int present = eth.begin(mac); controller reload

**Comment by AlekseyCanvas** [comment]
I use static IP, mask, gateway, dns... 
eth.config(ip, gateway, subnet, dns_1, dns_2);

**Comment by nopnop2002** [comment]
>This happens when the CS W5500 pin is connected to the D8 W5500 pin. 

D8(=GPIO15) used as Boot Mode Selection.
https://docs.espressif.com/projects/esptool/en/latest/esp8266/advanced-topics/boot-mode-selection.html


It must be Pulled Low/GND.
If these pins are set differently to shown, nothing on the ESP8266 will work as expected.
Use other GPIO.

```
connecting ethernet...
ethernet ip address: 192.168.10.192
ethernet subnetMask: 255.255.255.0
ethernet gateway: 192.168.10.1
```
