### ISSUE TITLE
How to implement Ethernet Events?

### ISSUE THREAD

**Issue by hubshi** [nopnop2002/esp8266_ethernet#7]
Hi!
Thank you for your repo, can you please give an example for ethernet events like WiFi event handling? 
I have tried to use statusChangeCB() function in the Wiznet5500lwIP class, but it seems beyond my expertise because it needs some arguments which i can't find any references for. Compiler returns the error as

`no suitable constructor exists to convert from "void ()" to "std::function<void (netif *)>"`

Best Regards.

**Comment by nopnop2002** [comment]
There are many events in the ESP32 WiFi object.

The esp8266 WiFi objects that I know of have these events, but all of them are valid when in AP mode.

I don't know about Wifi's status Change event in esp8266.


Ethernet does not have AP mode.

```
  // Call "onStationConnected" each time a station connects
  stationConnectedHandler = WiFi.onSoftAPModeStationConnected(&onStationConnected);

  // Call "onStationDisconnected" each time a station disconnects
  stationDisconnectedHandler = WiFi.onSoftAPModeStationDisconnected(&onStationDisconnected);

  // Call "onProbeRequestPrint" and "onProbeRequestBlink" each time
  // a probe request is received.
  // Former will print MAC address of the station and RSSI to Serial,
  // latter will blink an LED.
  probeRequestPrintHandler = WiFi.onSoftAPModeProbeRequestReceived(&onProbeRequestPrint);
  probeRequestBlinkHandler = WiFi.onSoftAPModeProbeRequestReceived(&onProbeRequestBlink);
```


https://github.com/esp8266/Arduino/blob/master/libraries/ESP8266WiFi/examples/WiFiEvents/WiFiEvents.ino

**Comment by hubshi** [comment]
Actually I need an example for statusChangeCB() callback function of Wiznet5500lwIP driver so we can implement the event handling for Ethernet instead of WiFi.

Best regards.

**Comment by nopnop2002** [comment]
WiFi and Ethernet have the same methods, the same properties, and the same events.

The methods, properties, and events that are not present in WiFi are also not present in Ethernet.

We cannot add methods, properties, or events.

WiFi doesn't have statusChangeCB, so Ethernet doesn't either.



The hierarchy of programs that use WiFi is as follows:

```
+----------------+
|  Application   |
+----------------+
| Network Object |
+----------------+
|      lwip      |
+----------------+
|   WiFi Driver  |
+----------------+ 
```

The hierarchy of programs that use Ethernet is as follows:

```
+----------------+
|  Application   |
+----------------+
| Network Object |
+----------------+
|      lwip      |
+----------------+
| Ethernet Driver|
+----------------+
```

Adding a callback function requires modification of NetworkObject, which is only possible with EspressIF.

You can use this library.

https://www.arduino.cc/reference/en/libraries/esp8266timerinterrupt/

Work fine.
You can retrieve eth.status periodically.

https://github.com/nopnop2002/esp8266_ethernet/tree/master/EthernetStatusCallBack

**Comment by hubshi** [comment]
Well , if you are using platformIO , you can find that both Ethernet and WiFi have statusChangeCB method. Anyway thank you for your support and the example. 

Best regards

**Comment by nopnop2002** [comment]
>you can find that both Ethernet and WiFi have statusChangeCB method

I can't find it.


Can you point me to a web page regarding this?

**Comment by hubshi** [comment]
Sure ! 

![IMG_20240709_141849.jpg](https://github.com/nopnop2002/esp8266_ethernet/assets/1032171/a3c53486-439d-4cd3-9a5c-a37e0fcd413d)

![IMG_20240709_141812.jpg](https://github.com/nopnop2002/esp8266_ethernet/assets/1032171/5ff0bacd-7a15-4c48-8149-f6425da969d1)

**Comment by hubshi** [comment]
I didn't find anything about it in my search on Google or whatsoever. But in platformIO you can find the method

**Comment by nopnop2002** [comment]
Thank you for information.

statusChangeCB is a static bool function, so it cannot be called externally.

We can’t use this function.
